#!/bin/bash

# Muestra el menu general
_menu()
{
    echo "Selecciona una opcion:"
    echo
    echo "1) Activar Apache"
    echo "2) Desactivar Apache"
    echo "3) Volver al menu principal"
    echo "4) Salir"
    echo -n "Indica una opcion: "
}

# Muestra la opcion seleccionada del menu
_mostrarResultado()
{
    clear
    echo ""
    echo "------------------------------------"
    echo "Has seleccionado la opcion $1"
    echo "------------------------------------"
    echo ""
}

# opcion por defecto
opc="0"

# bucle mientas la opcion indicada sea diferente de 9 (salir)
until [ "$opc" -eq "4" ];
do
    case $opc in
        1)
           sudo chkconfig apache2 on
            _mostrarResultado $opc
                
            _menu
			echo ""
			echo "APACHE ACTIIVADO"
            ;;
        2)
      sudo chkconfig apache2 off
            _mostrarResultado $opc
         
            _menu
			echo ""
			echo "APACHE DESACTIVADO"
            ;;
        3)
       
            _mostrarResultado $opc
                   
            _menu
            ;;

        *)
            # Esta opcion se ejecuta si no es ninguna de las anteriores
            clear
            _menu
            ;;
    esac
    read opc
done
